# a custom CRD, installed by crd-install hook
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.my.test.com
  labels:
    app: my-test-crd
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  group: my.test.com
  version: v1alpha1
  names:
    kind: test
    plural: tests
  scope: Cluster

---

# when using the hook, an instane of this CRD can be created in the same chart
apiVersion: my.test.com/v1alpha1
kind: test
metadata:
  name: test-instance
spec:
  testing: some-value
